//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 05/18/2016 21:31:25
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Eurofurence.Companion
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Translations
    {
        
        private static ResourceLoader resourceLoader;
        
        static Translations()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Translations).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Translations");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Translations");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Event Schedule"
        /// </summary>
        public static string EventSchedule_Title
        {
            get
            {
                return resourceLoader.GetString("EventSchedule_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Dealers"
        /// </summary>
        public static string Dealers_Title
        {
            get
            {
                return resourceLoader.GetString("Dealers_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Convention Information"
        /// </summary>
        public static string ConventionInformation_Title
        {
            get
            {
                return resourceLoader.GetString("ConventionInformation_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Convention Info"
        /// </summary>
        public static string Info_Title
        {
            get
            {
                return resourceLoader.GetString("Info_Title");
            }
        }
    }
}
